name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
- uses: actions/checkout@v2
- name: Set up JDK 11
  uses: actions/setup-java@v2
  with:
    java-version: '11'
    distribution: 'adopt'
- name: Start SUT
run: java -jar ./artifacts/app-ibank-build-for-testers.jar &
- name: Chmod
run: chmod +x gradlew
- name: Headless test
run: ./gradlew test --info -Dselenide.headless=true
